TOP_DIR = ../../..
MODULE_TOP_DIR = .
include $(TOP_DIR)/env.mk

BUILD_TYPE = lib
BUILD_NAME = libpcre
CFLAGS_LOCAL_CP += -DNEWLINE=10 -DPOSIX_MALLOC_THRESHOLD=10
SUB_MOD =
SUB_DIR = 

include $(TOP_DIR)/rule.mk
